server:
  port: 2603
  servlet:
    context-path: /admin

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ecommerce_project?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
